### Analysis of an E-commerce Dataset

We have been provided with a combined e-commerce dataset. In this dataset, each user has the ability to post a rating and review for the products they purchased. Additionally, other users can evaluate the initial rating and review by expressing their trust or distrust.

This dataset includes a wealth of information for each user. Details such as their profile, ID, gender, city of birth, product ratings (on a scale of 1-5), reviews, and the prices of the products they purchased are all included. Moreover, for each product rating, we have information about the product name, ID, price, and category, the rating score, the timestamp of the rating and review, and the average helpfulness of the rating given by others (on a scale of 1-5).

The dataset is from several data sources, and we have merged all the data into a single CSV file named 'A Combined E-commerce Dataset.csv'. The structure of this dataset is represented in the header shown below.

| userId | gender | rating | review| item | category | helpfulness | timestamp | item_id | item_price | user_city|

    | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |  ---- |  ---- |  
    
#### Description of Fields

* __userId__ - the user's id
* __gender__ - the user's gender
* __rating__ - the user's rating towards the item
* __review__ - the user's review towards the item
* __item__ - the item's name
* __category__ - the category of the item
* __helpfulness__ - the average helpfulness of this rating
* __timestamp__ - the timestamp when the rating is created
* __item_id__ - the item's id
* __item_price__ - the item's price
* __user_city__ - the city of user's birth

Note that, a user may rate multiple items and an item may receive ratings and reviews from multiple users. The "helpfulness" is an average value based on all the helpfulness values given by others.

There are four questions to explore with the data as shown below.



<img src="data-relation.png" align="left" width="400"/>

 #### Q1. Remove missing data
 
Please remove the following records in the csv file: 
 
 * gender/rating/helpfulness is missing
 * review is 'none'

__Display the DataFrame, counting number of Null values in each column, and print the length of the data__ before and after removing the missing data.

In [85]:
# your code and solutions
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [86]:
orignal_df= pd.read_csv('The E-commerce Dataset.csv')
orignal_df.info

<bound method DataFrame.info of        userId  timestamp                                    review  \
0        4051      12807                 Great job for what it is!
1        4052     122899               Free Access Worth your Time
2          33      12700             AOL..I love you!!!!!!!!!!!!
3          33      21000              EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300           Blair Witch...Oh Come On.......
...       ...        ...                                       ...
19995   10805      50600                 The Upper Class Fast Food
19996   10806      82201             What more can you ask for????
19997   10806      82201          Excellent steak for a good price
19998   10807      31504                     Different story world
19999   10808      10200  Boldly Displaying Sigourneys Cleavage ..

                                                    item  rating  helpfulness  \
0                                                   eBay     5.0          2.0
1                                                NetZero     5.0          0.0
2                                   AOL (America Online)     5.0          4.0
3                                                   eBay     5.0          4.0
4                                    Blair Witch Project     1.0          4.0
...                                                  ...     ...          ...
19995                                            Wendy's     2.0          3.0
19996                                       Olive Garden     4.0          0.0
19997                                 Outback Steakhouse     4.0          3.0
19998  J. K. Rowling - Harry Potter and the Sorcerer'...     4.0          0.0
19999                                       Galaxy Quest     4.0          0.0

      gender                  category  item_id  item_price  user_city
0          F  Online Stores & Services       88      149.00         39
1          F  Online Stores & Services       46       53.00         39
2          F  Online Stores & Services        0      145.84         31
3          F  Online Stores & Services       88      149.00         31
4          F                    Movies       12       44.00         31
...      ...                       ...      ...         ...        ...
19995      F     Restaurants & Gourmet       84       69.00         18
19996      M     Restaurants & Gourmet       49       32.00         28
19997      M     Restaurants & Gourmet       50       25.00         28
19998      M                     Books       36       96.00         27
19999      M                    Movies       29       67.00         11

[20000 rows x 11 columns]>

In [87]:
orignal_df.isnull().sum()

userId          0
timestamp       0
review          0
item            0
rating         17
helpfulness    22
gender         27
category        0
item_id         0
item_price      0
user_city       0
dtype: int64

In [88]:
df1=orignal_df.dropna()
df1.isnull().sum()

userId         0
timestamp      0
review         0
item           0
rating         0
helpfulness    0
gender         0
category       0
item_id        0
item_price     0
user_city      0
dtype: int64

In [89]:
for x in df1['review'] :
    if x=='none':
      print(x)

none
none
none
none
none
none
none
none
none
none
none
none
none
none
none
none
none
none

In [90]:
df2=df1.drop(index=df1[df1['review']=='none'].index)
for x in df2['review'] :
    if x=='none':
      print(x)
df2.isnull().sum()

userId         0
timestamp      0
review         0
item           0
rating         0
helpfulness    0
gender         0
category       0
item_id        0
item_price     0
user_city      0
dtype: int64

#### Q2. Descriptive statistics

With the cleaned data in Q1, please provide the data summarization as below:

* Q2.1 total number of unique users, unique reviews, unique items, and unique categories
* Q2.2 descriptive statistics, e.g., the total number, mean, std, min and max regarding all rating records
* Q2.3 descriptive statistics, e.g., mean, std, max, and min of the number of items rated by different genders 
* Q2.4 descriptive statistics, e.g., mean, std, max, min of the number of ratings that received by each items

In [ ]:
# your code and solutions

In [ ]:
#Q2.1 total number of unique users, unique reviews, unique items, and unique categories
df2

In [ ]:
pd.value_counts(df2['userId'])
len(df2['userId'].unique())

In [ ]:
len(df2['review'].unique())

In [ ]:
pd.value_counts(df2['category'])
len(df2['category'].unique())

In [ ]:
#Q2.2 descriptive statistics, e.g., the total number, mean, std, min and max regarding all rating records

In [ ]:

print("total number:",len(df2['rating']),"MEAN: ",df2['rating'].mean(),"STD: ",df2['rating'].std(),"Min: ",df2['rating'].min(),"MAX: ",df2['rating'].max())

In [ ]:
#Q2.3 descriptive statistics, e.g., mean, std, max, and min of the number of items rated by different genders

In [ ]:
Males=df2.drop(index=df2[df1['gender']=='F'].index)
Males

In [ ]:
print("total number:",len(Males['rating']),"MEAN: ",Males['rating'].mean(),"STD: ",Males['rating'].std(),"Min: ",Males['rating'].min(),"MAX: ",Males['rating'].max())

In [ ]:
Females=df2.drop(index=df2[df1['gender']=='M'].index)
Females

In [ ]:
print("total number:",len(Females['rating']),"MEAN: ",Females['rating'].mean(),"STD: ",Females['rating'].std(),"Min: ",Females['rating'].min(),"MAX: ",Females['rating'].max())

In [ ]:
#Q2.4 descriptive statistics, e.g., mean, std, max, min of the number of ratings that received by each items

In [ ]:
print(df2.groupby(['item'])['rating'].min())
print(df2.groupby(['item'])['rating'].max())
print(df2.groupby(['item'])['rating'].mean())
print(df2.groupby(['item'])['rating'].std())

#### Q3. Plotting and Analysis

Please try to explore the correlation between gender/helpfulness/category and ratings; for instance, do female/male users tend to provide higher ratings than male/female users? Hint: you may use the boxplot function to plot figures for comparison (___Challenge___)
    
You may need to select the most suitable graphic forms for ease of presentation. Most importantly, for each figure or subfigure, please summarise ___what each plot shows___ (i.e. observations and explanations). Finally, you may need to provide an overall summary of the data.

In [ ]:
# gender-rating correlation 
df2.boxplot("rating", by="gender") 
plt.xticks(rotation=90)

In [ ]:
#helpfulness-rating correlation 
df2.boxplot("rating", by="helpfulness") 
plt.xticks(rotation=90)

In [ ]:
# your code and solutions

#### Q4. Detect and remove outliers

We may define outlier users, reviews and items with three rules (if a record meets one of the rules, it is regarded as an outlier):

* reviews of which the helpfulness is no more than 2
* users who rate less than 7 items
* items that receives less than 11 ratings 
 
Please remove the corresponding records in the csv file that involves outlier users, reviews and items. After that, __print the length of the data__.

In [ ]:
# your code and solutions

In [99]:
remove_outlier_df = df2.drop(index=df2[df2['helpfulness']<=2].index)

remove_outlier_df

,userId,timestamp,review,item,rating,helpfulness,gender,category,item_id,item_price,user_city
2,33,12700,AOL..I love you!!!!!!!!!!!!,AOL (America Online),5.0,4.0,F,Online Stores & Services,0,145.84,31
3,33,21000,EBAY!!! I LOVE YOU!!!! :-)*,eBay,5.0,4.0,F,Online Stores & Services,88,149.00,31
4,33,22300,Blair Witch...Oh Come On.......,Blair Witch Project,1.0,4.0,F,Movies,12,44.00,31
6,33,32100,Go down under Mateys!!!!!,Outback Steakhouse,5.0,4.0,F,Restaurants & Gourmet,50,25.00,31
9,4053,22304,The best on the web.,Amazon.com,5.0,3.0,F,Online Stores & Services,3,129.82,22
...,...,...,...,...,...,...,...,...,...,...,...
19992,10805,11900,R.I.P,MTV,1.0,4.0,F,Media,39,138.00,18
19993,10805,12000,Leave them be...,Teletubbies,5.0,4.0,F,Kids & Family,76,48.25,18
19994,10805,50500,"Thank you, Drive Thru Please",McDonald's,3.0,3.0,F,Restaurants & Gourmet,41,30.74,18
19995,10805,50600,The Upper Class Fast Food,Wendy's,2.0,3.0,F,Restaurants & Gourmet,84,69.00,18
19997,10806,82201,Excellent steak for a good price,Outback Steakhouse,4.0,3.0,M,Restaurants & Gourmet,50,25.00,28

In [128]:
#users who rate less than 7 items
Ratings=remove_outlier_df.groupby(['userId']).agg({'rating':'count'})
Ratings

TypeError: '<=' not supported between instances of 'str' and 'int'

       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.
...       ...        ...                               ...
19992   10805      11900                             R.I.P
19993   10805      12000                  Leave them be...
19994   10805      50500      Thank you, Drive Thru Please
19995   10805      50600         The Upper Class Fast Food
19997   10806      82201  Excellent steak for a good price

                       item  rating  helpfulness gender  \
2      AOL (America Online)     5.0          4.0      F
3                      eBay     5.0          4.0      F
4       Blair Witch Project     1.0          4.0      F
6        Outback Steakhouse     5.0          4.0      F
9                Amazon.com     5.0          3.0      F
...                     ...     ...          ...    ...
19992                   MTV     1.0          4.0      F
19993           Teletubbies     5.0          4.0      F
19994            McDonald's     3.0          3.0      F
19995               Wendy's     2.0          3.0      F
19997    Outback Steakhouse     4.0          3.0      M

                       category  item_id  item_price  user_city
2      Online Stores & Services        0      145.84         31
3      Online Stores & Services       88      149.00         31
4                        Movies       12       44.00         31
6         Restaurants & Gourmet       50       25.00         31
9      Online Stores & Services        3      129.82         22
...                         ...      ...         ...        ...
19992                     Media       39      138.00         18
19993             Kids & Family       76       48.25         18
19994     Restaurants & Gourmet       41       30.74         18
19995     Restaurants & Gourmet       84       69.00         18
19997     Restaurants & Gourmet       50       25.00         28

[13643 rows x 11 columns]
       userId  timestamp                            review  \
2          33      12700     AOL..I love you!!!!!!!!!!!!
3          33      21000      EBAY!!!  I LOVE YOU!!!! :-)*
4          33      22300   Blair Witch...Oh Come On.......
6          33      32100         Go down under Mateys!!!!!
9        4053      22304              The best on the web.

In [ ]:

X = X[X.isin(userIds)]

XXXXXdf = XXXXX.count().reset_index(name= 'count') XXXXX_df.head()

items = XXXX >= 11['item'].tolist()

print(len(items))

XXXXoutlier_df = XXXXX.isin(items)

len (XXXXoutlier_df)

XXXXX.to_sv('A combined dataset from ecommerce dataset_cl